version: '3.2'
services:

  #frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    environment:
      SERVICE_NAME: frontend
      SERVICE_TAGS: dev
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - app-network
    volumes:
      - ./frontend:/var/www/html/frontend

  #PHP-backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html/backend
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html/backend
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:8.0.31
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #PHP my admin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumnes
volumes:
  dbdata:
    driver: local
